import type { Metadata } from 'next';

import Footer from '@/components/footer';
import Header from '@/components/header';
import ModalProvider from '@/providers/modal-provider';
import { Urbanist } from 'next/font/google';
import { ReactNode } from 'react';

import '../styles/globals.css';

const inter = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
